### ISSUE TITLE
Cleanup after bmlab tests were run

### ISSUE THREAD

**Issue by raimund-schluessler** [BrillouinMicroscopy/bmlab#23] opened 2021-05-05 12:11 UTC
Currently, after each run of the bmlab test suite, two folders starting with `tmpxxxx` are created in the BMicro (?) directory containing the Water.h5 test file and a corresponding session file. Would be good to clean that up after the tests have finished.

@matthias-baer Is this also happening for you?

**Comment by matthias-baer** [comment] 2021-05-05 13:17
Actually this tidy up should happen automatically. But on github actions with Windows, I got an exception in the tidy up process. I thought this is only some issue on the remote machine and didn't care because the VM is cleaned after the action anyways. So I just wrapped it with a try block. But obviously it generally happens with Windows. The issue is the shutil.rmtree command in the tmp_dir fixture. 

On Mac and Linux no such issue happens. I suspect there is some issue in h5py on Windows because it seems that the HDF file is not closed in time when leaving the with-context before shutil.rmtree tries to delete the temporary directory.

**Comment by raimund-schluessler** [comment] 2021-05-05 13:20
Hm, I just try to debug it. But couldn't get to the root cause yet. But what I noticed is that we seem to never close the session.h5 file anywhere. The raw data file is properly handled by the BrillouinFile destructor, but the session file handle is just a raw h5py handle and we never call `close()` on it. However, manually closing it directly after loading and saving doesn't make a difference regarding the file locks.

**Comment by matthias-baer** [comment] 2021-05-05 13:27
The handles of the session.h5 files are all wrapped in with-statements so that they are closed automatically when exiting the with-block. At least this is how it should be (and it works on Mac and Linux). 

I'm afraid this can only be debugged on a Windows machine. Do you have one? You can set a breakpoint in the method `h5py.files.File.__exit__`, which is the magic function that is performed when the with-block ends.

**Comment by raimund-schluessler** [comment] 2021-05-05 13:29
I am on Windows, yes. The problem seems to be the raw data file. Even after session.clear() is called, the H5 file is not released. The session file is properly closed and can be deleted.

**Comment by raimund-schluessler** [comment] 2021-05-05 13:31
Somehow, this destructor is never called: 
https://github.com/BrillouinMicroscopy/bmlab/blob/main/bmlab/file.py#L69-L76

**Comment by matthias-baer** [comment] 2021-05-05 13:32
Ok, then this may be a garbage collector issue. It's probably platform dependent, when the destructor is called.

**Comment by matthias-baer** [comment] 2021-05-05 13:34
How about removing the destructor and implementing some session.close() method which is to be called at the end of the application (or manually, if desired). Then session.close() would explicitly close the file?

**Comment by raimund-schluessler** [comment] 2021-05-05 13:35
> 
> 
> How about removing the destructor and implementing some session.close() method which is to be called at the end of the application (or manually, if desired). Then session.close() would explicitly close the file?

I was just about to do this 👍

**Comment by matthias-baer** [comment] 2021-05-05 13:42
Originally I had used temporary directories using the `tempfile` package of the standard library, in particular `tempfile.TemporaryDirectory`. This is much neater than the manual creation and deletion of a temporary folder. But then I ran into this file permission issue and originally I thought it is due to the exotic location that is used by tempfile.TemporaryDirectory. With the issue now solved, we could change the implementation back to tempfile.TemporaryDirectory. That would make sure that the tmp-dirs are not created somewhere in the project structure (even if they are .gitignored).

**Comment by raimund-schluessler** [comment] 2021-05-05 13:52
Closing the H5 file manually solves the issue. We just need to call `session.clear()` now in every test using a session.

I am fine with moving back to `tempfile`. For now, I am just happy that my project structure doesn't get spammed with temp dirs anymore 😉

**Closed** 2021-05-05 13:52 UTC
